import type { BalletClassSection, BalletClassType, BalletExerciseDefinition } from './types.js';

export interface BalletClassSectionPlan {
  readonly section: BalletClassSection;
  readonly count: number;
  readonly minimumStageIndex?: number;
}

export interface BalletClassTypeDefinition {
  readonly id: BalletClassType;
  readonly displayName: string;
  readonly description: string;
  readonly minimumStageIndex: number;
  readonly sections: readonly BalletClassSectionPlan[];
}

export const BALLET_CLASS_TYPE_CATALOG: readonly BalletClassTypeDefinition[] = [
  {
    id: 'REGULAR',
    displayName: 'Regular Ballet Class',
    description: 'A stage-aware class with barre, centre, and unlocked extensions.',
    minimumStageIndex: 0,
    sections: [
      { section: 'BARRE', count: 2 },
      { section: 'CENTRE', count: 2 },
      { section: 'ADAGIO', count: 1, minimumStageIndex: 4 },
      { section: 'TURNS', count: 1, minimumStageIndex: 5 },
      { section: 'ALLEGRO', count: 1, minimumStageIndex: 6 },
      { section: 'REPERTOIRE', count: 1, minimumStageIndex: 11 },
    ],
  },
  {
    id: 'TECHNIQUE',
    displayName: 'Technique Class',
    description: 'A focused sequence for technical placement and coordination.',
    minimumStageIndex: 0,
    sections: [
      { section: 'BARRE', count: 1 },
      { section: 'CENTRE', count: 1 },
      { section: 'TECHNIQUE', count: 2 },
    ],
  },
  {
    id: 'BARRE_FOCUS',
    displayName: 'Barre Focus',
    description: 'A structured barre-focused session.',
    minimumStageIndex: 0,
    sections: [{ section: 'BARRE', count: 3 }],
  },
  {
    id: 'CENTRE_FOCUS',
    displayName: 'Centre Focus',
    description: 'A stage-appropriate centre practice session.',
    minimumStageIndex: 0,
    sections: [{ section: 'CENTRE', count: 3 }],
  },
  {
    id: 'TURNS',
    displayName: 'Turns Class',
    description: 'A turns session with preparation matched to Academy stage.',
    minimumStageIndex: 4,
    sections: [
      { section: 'CENTRE', count: 1 },
      { section: 'TURNS', count: 2 },
    ],
  },
  {
    id: 'ALLEGRO',
    displayName: 'Jumps & Allegro Class',
    description: 'A stage-aware allegro and travelling-steps session.',
    minimumStageIndex: 5,
    sections: [
      { section: 'CENTRE', count: 1 },
      { section: 'ALLEGRO', count: 2 },
    ],
  },
  {
    id: 'CONDITIONING',
    displayName: 'Conditioning Class',
    description: 'A fictional, low-detail conditioning gameplay session.',
    minimumStageIndex: 0,
    sections: [{ section: 'CONDITIONING', count: 2 }],
  },
  {
    id: 'REPERTOIRE',
    displayName: 'Repertoire Class',
    description: 'Original fictional variations for repertoire-stage students.',
    minimumStageIndex: 11,
    sections: [
      { section: 'CENTRE', count: 1 },
      { section: 'REPERTOIRE', count: 2 },
    ],
  },
  {
    id: 'ASSESSMENT_PREPARATION',
    displayName: 'Assessment Preparation',
    description: 'A preparatory class foundation; it is not a formal assessment.',
    minimumStageIndex: 0,
    sections: [
      { section: 'BARRE', count: 1 },
      { section: 'CENTRE', count: 1 },
      { section: 'TECHNIQUE', count: 1 },
    ],
  },
];

export const BALLET_CLASS_EXERCISES: readonly BalletExerciseDefinition[] = [
  exercise(
    'barre-plie-foundations',
    'Plié Foundations',
    'Pliés',
    'BARRE',
    'A measured foundations combination.',
    1,
    0,
    { technique: 3, flexibility: 1, stamina: 1 },
    ['GENERAL_WARM_UP', 'BARRE'],
    ['POSTURE_PLACEMENT', 'TECHNIQUE'],
  ),
  exercise(
    'barre-tendu-foundations',
    'Tendu Foundations',
    'Tendus',
    'BARRE',
    'A steady tendu phrase with clear counts.',
    1,
    0,
    { technique: 4, musicality: 1 },
    ['GENERAL_WARM_UP', 'BARRE'],
    ['FOOTWORK', 'TIMING'],
  ),
  exercise(
    'barre-glisse-phrase',
    'Glissé Phrase',
    'Dégagés / Glissés',
    'BARRE',
    'A stage-appropriate glissé phrase.',
    2,
    1,
    { technique: 3, musicality: 1, stamina: 1 },
    ['GENERAL_WARM_UP', 'MOBILITY', 'BARRE'],
    ['FOOTWORK', 'COORDINATION'],
  ),
  exercise(
    'barre-rond-de-jambe',
    'Rond de Jambe Study',
    'Rond de jambe',
    'BARRE',
    'A controlled circular phrase.',
    2,
    2,
    { technique: 3, flexibility: 2 },
    ['MOBILITY', 'BARRE'],
    ['TECHNIQUE', 'COORDINATION'],
  ),
  exercise(
    'barre-fondu-control',
    'Fondu Control',
    'Fondu',
    'BARRE',
    'A balanced fondu combination.',
    3,
    3,
    { technique: 3, flexibility: 1, stamina: 1 },
    ['GENERAL_WARM_UP', 'BALANCE', 'BARRE'],
    ['BALANCE', 'TECHNIQUE'],
  ),
  exercise(
    'barre-frappe-rhythm',
    'Frappé Rhythm',
    'Frappé',
    'BARRE',
    'A crisp rhythm study at the barre.',
    3,
    4,
    { technique: 3, musicality: 2 },
    ['GENERAL_WARM_UP', 'BARRE'],
    ['TIMING', 'FOOTWORK'],
  ),
  exercise(
    'barre-adagio-line',
    'Adagio Line',
    'Adagio at the barre',
    'BARRE',
    'A sustained line and musical phrasing study.',
    4,
    6,
    { technique: 3, flexibility: 2, musicality: 2 },
    ['MOBILITY', 'CORE_ACTIVATION', 'BARRE'],
    ['BALANCE', 'MUSICALITY'],
  ),
  exercise(
    'barre-grand-battement-control',
    'Grand Battement Control',
    'Grands battements',
    'BARRE',
    'A controlled grand battement sequence.',
    4,
    7,
    { technique: 3, flexibility: 2, stamina: 1 },
    ['GENERAL_WARM_UP', 'MOBILITY', 'BARRE'],
    ['TECHNIQUE', 'BALANCE'],
  ),
  exercise(
    'centre-port-de-bras',
    'Port de Bras Foundations',
    'Port de bras',
    'CENTRE',
    'A gentle port de bras phrase with simple counts.',
    1,
    0,
    { technique: 2, musicality: 2 },
    ['GENERAL_WARM_UP', 'CORE_ACTIVATION'],
    ['POSTURE_PLACEMENT', 'MUSICALITY'],
  ),
  exercise(
    'centre-foundations',
    'Centre Foundations',
    'Centre practice',
    'CENTRE',
    'A simple centre-floor coordination phrase.',
    1,
    0,
    { technique: 3, musicality: 1, stamina: 1 },
    ['GENERAL_WARM_UP', 'BALANCE'],
    ['COORDINATION', 'TIMING'],
  ),
  exercise(
    'centre-adagio-study',
    'Adagio Study',
    'Adagio',
    'ADAGIO',
    'A measured adagio phrase.',
    2,
    2,
    { technique: 2, flexibility: 2, musicality: 2 },
    ['MOBILITY', 'CORE_ACTIVATION', 'BALANCE'],
    ['BALANCE', 'MUSICALITY'],
  ),
  exercise(
    'centre-balance-phrase',
    'Balance Phrase',
    'Balance work',
    'CENTRE',
    'A steady balance and placement phrase.',
    2,
    2,
    { technique: 3, flexibility: 1, stamina: 1 },
    ['GENERAL_WARM_UP', 'BALANCE'],
    ['BALANCE', 'POSTURE_PLACEMENT'],
  ),
  exercise(
    'centre-travelling-steps',
    'Travelling Steps',
    'Travelling steps',
    'CENTRE',
    'A travelling phrase matched to the current stage.',
    2,
    3,
    { technique: 3, musicality: 1, stamina: 2 },
    ['GENERAL_WARM_UP', 'CORE_ACTIVATION'],
    ['FOOTWORK', 'COORDINATION'],
  ),
  exercise(
    'technique-coordination',
    'Coordination Combination',
    'Technique',
    'TECHNIQUE',
    'A short coordination phrase with a clear rhythm.',
    2,
    2,
    { technique: 3, musicality: 2, stamina: 1 },
    ['GENERAL_WARM_UP', 'CORE_ACTIVATION'],
    ['COORDINATION', 'TIMING'],
  ),
  exercise(
    'technique-placement',
    'Placement Study',
    'Technique',
    'TECHNIQUE',
    'A placement-focused studio study.',
    2,
    1,
    { technique: 4, flexibility: 1 },
    ['MOBILITY', 'BALANCE'],
    ['POSTURE_PLACEMENT', 'TECHNIQUE'],
  ),
  exercise(
    'turns-preparation',
    'Turn Preparation',
    'Pirouette preparation',
    'TURNS',
    'A non-pointe turns preparation phrase.',
    2,
    4,
    { technique: 3, performance: 1, stamina: 1 },
    ['GENERAL_WARM_UP', 'CORE_ACTIVATION', 'BALANCE', 'TURNS'],
    ['BALANCE', 'TURN_CONTROL'],
  ),
  exercise(
    'turns-pirouette-study',
    'Pirouette Study',
    'Pirouettes',
    'TURNS',
    'A stage-gated pirouette gameplay study.',
    4,
    9,
    { technique: 3, performance: 2, stamina: 1 },
    ['GENERAL_WARM_UP', 'CORE_ACTIVATION', 'BALANCE', 'TURNS'],
    ['TURN_CONTROL', 'BALANCE'],
  ),
  exercise(
    'allegro-petit',
    'Petit Allegro Phrase',
    'Petit allegro',
    'ALLEGRO',
    'A stage-appropriate petit allegro phrase.',
    3,
    5,
    { technique: 3, musicality: 1, stamina: 2 },
    ['GENERAL_WARM_UP', 'CORE_ACTIVATION', 'JUMPS'],
    ['JUMP_CONTROL', 'COORDINATION'],
  ),
  exercise(
    'allegro-travelling',
    'Travelling Allegro',
    'Jumps / Leaps',
    'ALLEGRO',
    'A fictional travelling allegro sequence.',
    4,
    8,
    { technique: 2, performance: 2, stamina: 2 },
    ['GENERAL_WARM_UP', 'CORE_ACTIVATION', 'BALANCE', 'JUMPS'],
    ['JUMP_CONTROL', 'TIMING'],
  ),
  exercise(
    'allegro-grand',
    'Grand Allegro Phrase',
    'Grand allegro',
    'ALLEGRO',
    'A stage-gated grand allegro phrase.',
    5,
    11,
    { technique: 2, performance: 2, stamina: 3 },
    ['GENERAL_WARM_UP', 'CORE_ACTIVATION', 'BALANCE', 'JUMPS'],
    ['JUMP_CONTROL', 'COORDINATION'],
  ),
  exercise(
    'conditioning-focus',
    'Core & Focus Sequence',
    'Conditioning',
    'CONDITIONING',
    'A fictional focus sequence for gameplay readiness.',
    1,
    0,
    { technique: 1, stamina: 2 },
    ['GENERAL_WARM_UP', 'CORE_ACTIVATION'],
    ['COORDINATION', 'TIMING'],
  ),
  exercise(
    'conditioning-balance',
    'Balance & Placement Sequence',
    'Conditioning',
    'CONDITIONING',
    'A simple balance-themed studio sequence.',
    1,
    0,
    { technique: 2, flexibility: 1 },
    ['GENERAL_WARM_UP', 'BALANCE'],
    ['BALANCE', 'POSTURE_PLACEMENT'],
  ),
  exercise(
    'repertoire-moonlit-variation',
    'Moonlit Studio Variation',
    'Original repertoire',
    'REPERTOIRE',
    'An original fictional variation focused on musical phrasing.',
    3,
    11,
    { musicality: 2, performance: 2, technique: 1 },
    ['GENERAL_WARM_UP', 'MOBILITY', 'CORE_ACTIVATION'],
    ['MUSICALITY', 'TECHNIQUE'],
  ),
  exercise(
    'repertoire-rose-garden',
    'Rose Garden Variation',
    'Original repertoire',
    'REPERTOIRE',
    'An original fictional variation emphasizing interpretation.',
    4,
    12,
    { musicality: 2, performance: 3, technique: 1 },
    ['GENERAL_WARM_UP', 'CORE_ACTIVATION', 'BALANCE'],
    ['MUSICALITY', 'COORDINATION'],
  ),
  exercise(
    'repertoire-final-bow',
    'Final Bow Variation',
    'Original repertoire',
    'REPERTOIRE',
    'An original fictional performance phrase.',
    5,
    15,
    { musicality: 2, performance: 3, stamina: 2 },
    ['GENERAL_WARM_UP', 'CORE_ACTIVATION', 'BALANCE'],
    ['TIMING', 'MUSICALITY'],
  ),
];

function exercise(
  id: string,
  displayName: string,
  family: string,
  section: BalletClassSection,
  description: string,
  difficulty: number,
  minimumStageIndex: number,
  skillWeights: BalletExerciseDefinition['skillWeights'],
  preparationRequirements: BalletExerciseDefinition['preparationRequirements'],
  correctionCategories: BalletExerciseDefinition['correctionCategories'],
): BalletExerciseDefinition {
  return {
    id,
    displayName,
    family,
    section,
    description,
    difficulty,
    minimumStageIndex,
    skillWeights,
    preparationRequirements,
    correctionCategories,
    evidenceCode: id,
  };
}
