export const NOELIA_COPY = {
  embedFooter: 'Noélia · ballet studio',
  helpTitle: 'A little studio guide',
  helpIntro: 'Choose a command to see what we can do together:',
  balanceTitle: 'Your Ballet Slippers',
  dailyTitle: 'A little reward for showing up',
  dailyClaimed: 'Daily reward claimed',
  dailyReplayed: 'Your daily reward is already recorded',
  balletStatusTitle: 'Studio progress',
  balletActivitiesTitle: 'Today at the studio',
  balletPracticeComplete: 'Practice complete',
  balletPracticeReplayed: 'Practice already recorded',
  shopTitle: 'The studio boutique',
  shopEmpty: 'The collection has no pieces in that category just yet.',
  shopItemTitle: 'A closer look',
  shopPurchaseComplete: 'A new keepsake is yours',
  shopPurchaseReplayed: 'Your purchase is already recorded',
  inventoryTitle: 'Your keepsakes',
  inventoryEmpty:
    'Your collection is waiting for its first keepsake. Browse `/shop` whenever you are ready.',
  wardrobeTitle: 'Your studio look',
  wardrobeEmpty: 'Your wardrobe is ready for its first look.',
  profileTitle: 'Your studio profile',
  marketTitle: 'The studio exchange',
  marketEmpty: 'No pieces are listed just now. Your studio exchange is taking a quiet moment.',
  marketListingCreated: 'Your piece is on the exchange',
  marketListingCancelled: 'Your piece is back in your wardrobe',
  marketPurchaseComplete: 'A new piece is yours',
  marketPurchaseReplayed: 'That exchange is already recorded',
  performanceTitle: 'A moment on stage',
  performanceBrowseTitle: 'Studio performances',
  performanceHistoryTitle: 'Your performance notes',
  performanceEmpty: 'No performances are available yet.',
  performanceHistoryEmpty: 'Your stage history is waiting for its first performance.',
  shopCollectionsTitle: 'Ballet collections',
  shopCollectionsEmpty: 'The studio collections are not available just now.',
  wardrobePresetsTitle: 'Saved studio looks',
  wardrobePresetsEmpty: 'No outfit presets yet. Save your current outfit to keep a look.',
  wardrobePresetSaved: 'Your studio look is saved',
  wardrobePresetApplied: 'Your studio look is ready',
  wardrobePresetRenamed: 'Your preset has a new name',
  wardrobePresetDeleted: 'Your preset was removed',
  wardrobeCleared: 'Your wardrobe is ready for a fresh look',
  wardrobeClearReplay: 'That wardrobe clear is already recorded.',
  wardrobeClearRemoved: (count: number) =>
    `Removed ${count} equipped ${count === 1 ? 'piece' : 'pieces'}.`,
  wardrobePresetListEntry: (presetId: string, name: string, itemCount: number) =>
    `#${presetId} **${name}** · ${itemCount} ${itemCount === 1 ? 'piece' : 'pieces'}`,
  wardrobePresetSummary: (presetId: string, name: string, itemCount: number, replayed: boolean) =>
    `#${presetId} **${name}** · ${itemCount} ${itemCount === 1 ? 'piece' : 'pieces'}${replayed ? ' · already saved' : ''}`,
  wardrobePresetAppliedSummary: (
    presetId: string,
    name: string,
    itemNames: string,
    replayed: boolean,
  ) =>
    `#${presetId} **${name}**\n${itemNames}${replayed ? '\nThat look was already applied.' : ''}`,
  wardrobePresetRenameSummary: (presetId: string, name: string) => `#${presetId} **${name}**`,
  wardrobePresetDeleteSummary: (presetId: string, name: string) => `#${presetId} **${name}**`,
  currentLook: 'Current look',
} as const;

export const NOELIA_PRESENCE = [
  'At the barre, finding my balance',
  'Tying a satin ribbon before class',
  'Practising port de bras, one count at a time',
  'Saving a soft rose glow for rehearsal',
] as const;
