export const NOELIA_COPY = {
  embedFooter: 'Noélia',
  helpTitle: 'Help',
  helpIntro: 'Choose a command.',
  balanceTitle: 'Your Ballet Slippers',
  dailyTitle: 'Daily claim',
  dailyClaimed: 'Daily reward claimed',
  dailyReplayed: 'Your daily reward is already recorded',
  balletStatusTitle: 'Studio progress',
  balletAcademyTitle: 'Maison Noélia',
  balletActivitiesTitle: 'Today at the studio',
  balletPracticeComplete: 'Practice complete',
  balletPracticeReplayed: 'Practice already recorded',
  shopTitle: 'The shop',
  shopEmpty: 'No items are available in that category right now.',
  shopItemTitle: 'Item details',
  shopPurchaseComplete: 'Purchase complete',
  shopPurchaseReplayed: 'Your purchase is already recorded',
  inventoryTitle: 'Inventory',
  inventoryEmpty: 'Your inventory is empty. Browse `/shop` when you want to.',
  wardrobeTitle: 'Wardrobe',
  wardrobeEmpty: 'No outfit is equipped.',
  profileTitle: 'Profile',
  marketTitle: 'Marketplace',
  marketEmpty: 'No listings are available right now.',
  marketListingCreated: 'Listing created',
  marketListingCancelled: 'Listing cancelled',
  marketPurchaseComplete: 'Purchase complete',
  marketPurchaseReplayed: 'That exchange is already recorded',
  performanceTitle: 'A moment on stage',
  performanceBrowseTitle: 'Studio performances',
  performanceHistoryTitle: 'Your performance notes',
  performanceEmpty: 'No performances are available yet.',
  performanceHistoryEmpty: 'Your stage history is waiting for its first performance.',
  shopCollectionsTitle: 'Collections',
  shopCollectionsEmpty: 'Collections are not available right now.',
  wardrobePresetsTitle: 'Saved outfits',
  wardrobePresetsEmpty: 'No outfit presets yet. Save your current outfit to keep a look.',
  wardrobePresetSaved: 'Outfit saved',
  wardrobePresetApplied: 'Outfit applied',
  wardrobePresetRenamed: 'Your preset has a new name',
  wardrobePresetDeleted: 'Your preset was removed',
  wardrobeCleared: 'Your wardrobe is ready for a fresh look',
  wardrobeClearReplay: 'That wardrobe clear is already recorded.',
  wardrobeClearRemoved: (count: number) =>
    `Removed ${count} equipped ${count === 1 ? 'piece' : 'pieces'}.`,
  wardrobePresetListEntry: (presetId: string, name: string, itemCount: number) =>
    `#${presetId} **${name}** · ${itemCount} ${itemCount === 1 ? 'piece' : 'pieces'}`,
  wardrobePresetSummary: (presetId: string, name: string, itemCount: number, replayed: boolean) =>
    `#${presetId} **${name}** · ${itemCount} ${itemCount === 1 ? 'piece' : 'pieces'}${replayed ? ' · already saved' : ''}`,
  wardrobePresetAppliedSummary: (
    presetId: string,
    name: string,
    itemNames: string,
    replayed: boolean,
  ) =>
    `#${presetId} **${name}**\n${itemNames}${replayed ? '\nThat look was already applied.' : ''}`,
  wardrobePresetRenameSummary: (presetId: string, name: string) => `#${presetId} **${name}**`,
  wardrobePresetDeleteSummary: (presetId: string, name: string) => `#${presetId} **${name}**`,
  achievementsTitle: 'Milestones',
  achievementsIntro: 'Milestones you have earned.',
  achievementsEmpty: 'No milestones unlocked yet.',
  achievementFeatureTitle: 'Your featured milestone',
  achievementFeatureCleared: 'Your featured milestone was cleared.',
  achievementListEntry: (
    badgeMark: string,
    displayName: string,
    achievementId: string,
    unlocked: boolean,
    featured: boolean,
  ) =>
    `${badgeMark} **${displayName}** · ${unlocked ? 'Unlocked' : 'Not yet unlocked'}${featured ? ' · Featured' : ''}\nID: ${achievementId}`,
  achievementFeaturedSummary: (badgeMark: string, displayName: string) =>
    `${badgeMark} **${displayName}** is now featured on your profile.`,
  profileStatsTitle: 'Ballet stats',
  profileStatLine: (stats: readonly string[]) => stats.join(' · '),
  profileCollectionProgress: (completed: number, total: number) =>
    `Collections completed: ${completed}/${total}`,
  profileFeaturedAchievement: (badgeMark: string, displayName: string) =>
    `Featured badge: ${badgeMark} **${displayName}**`,
  profileNoFeaturedAchievement: 'No featured badge selected.',
  profileMarriage: (partnerUserId: string | null) =>
    partnerUserId === null ? 'Relationship: not married' : `Partner: <@${partnerUserId}>`,
  currentLook: 'Current look',
  marriageTitle: 'Relationship',
  marriageProposal: (proposerUserId: string, targetUserId: string) =>
    `<@${proposerUserId}> sent <@${targetUserId}> a relationship proposal.\n\nOnly <@${targetUserId}> can accept or decline. The sender can cancel it.`,
  marriageAccepted: 'The proposal was accepted. Congratulations to you both!',
  marriageDeclined: 'The proposal was declined.',
  marriageCancelled: 'The sender cancelled the pending proposal.',
  marriagePending: 'That proposal is still waiting for an answer.',
  marriageNone: 'No active relationship is recorded for you.',
  marriageStatus: (partnerUserId: string, since: string) =>
    `Your partner is <@${partnerUserId}>. Together since ${since}.`,
  marriageDivorced: 'The relationship has ended. Your relationship history remains recorded.',
  marriageAcceptButton: 'Accept',
  marriageDeclineButton: 'Decline',
  marriageCancelButton: 'Cancel proposal',
} as const;

export const NOELIA_PERSONA_FALLBACKS: Readonly<Record<string, readonly string[]>> = {
  'ballet:status_view': ['Progress.', 'I noticed.', 'Better than last time.'],
  'ballet:academy_view': [
    'The foundation matters. Keep going.',
    'That stage is earned one class at a time.',
    'The basics are still the point.',
  ],
  'ballet:activities_view': [
    'Choose your next class.',
    'Read the requirements first.',
    'One class. Then the next.',
  ],
  'ballet:practice_complete': [
    'Better.',
    'Again, if you want it cleaner.',
    'That was good. I noticed.',
    'Quite good. Almost looked easy.',
    'It was fine. We can make it better.',
    'Très bien.',
  ],
  'ballet:practice_replayed': [
    'Already recorded.',
    'Your practice is saved.',
    'No need to repeat it. It is there.',
  ],
  'ballet:class_preparing': [
    'Mark your preparation, then begin when ready.',
    'You can continue without marking every area.',
    'Ready? Then start.',
  ],
  'ballet:class_in_progress': [
    'One exercise at a time.',
    'Keep the counts in mind.',
    'Keep your placement.',
  ],
  'ballet:class_result': [
    'Noted. Keep that correction for the next exercise.',
    'Again.',
    'Better. Continue.',
    'That was close. You know what to fix.',
  ],
  'ballet:class_review': [
    'The review is based on your recorded work.',
    'There. Your class is on record.',
    'Some things were better than others. You can see which.',
  ],
  'ballet:class_abandoned': [
    'Session closed. Completed work remains recorded.',
    'You can start another class when ready.',
  ],
  'performance:attempt_complete': [
    'That was good. I noticed.',
    'A clean finish. Finally.',
    'You held the room.',
    'Almost effortless. Almost.',
    'The lights did their job.',
  ],
  'performance:attempt_replayed': [
    'Already recorded.',
    'Your performance is in the record.',
    'No second attempt was needed.',
  ],
  'performance:browse': [
    'Choose a performance.',
    'The stage is available.',
    'Pick one. I am curious.',
  ],
  'performance:history_view': [
    'Your performance record.',
    'All the recorded performances, in one place.',
    'I noticed the progress.',
  ],
  'wardrobe:academy_uniform:ready': ['Ready.', 'That works.', 'Good. Keep it neat.'],
  'wardrobe:academy_uniform:missing': [
    'The required pieces are still missing. Check the list.',
    'Your uniform is not ready yet.',
    'Check which required pieces you still need.',
  ],
  'wardrobe:academy_uniform_claimed': [
    'You are set.',
    'There. Ready for class.',
    'That works. Keep it in order.',
  ],
  'wardrobe:outfit_view': [
    'Interesting choice.',
    'It is fine.',
    'No, keep it. It suits you.',
    'I do not judge. I notice.',
    'You chose that? It works.',
  ],
  'wardrobe:item_equipped': [
    'Better.',
    'That works.',
    'Good. A more deliberate choice.',
    'It catches the eye. I noticed.',
  ],
  'wardrobe:presets_list': ['Options. Good.', 'Choose one.', 'That one is better.'],
  'shop:browse': [
    'Interesting.',
    'Some of these are fine.',
    'That caught your eye?',
    'The details decide whether it works.',
  ],
  'shop:item_details': [
    'It works.',
    'The finish is better than expected.',
    'I would keep looking.',
  ],
  'daily:claim_complete': ['You made it.', 'Claim recorded.', 'There. Done.'],
  'daily:claim_replayed': ['Already recorded.', 'It is already yours.', 'No second claim needed.'],
  'shop:collections_view': [
    'A collection. I see.',
    'Some of these are worth keeping.',
    'Look through them.',
  ],
  'shop:purchase_complete': [
    'Good choice.',
    'That one was worth it.',
    'You chose well. I noticed.',
    'It should work with what you have.',
  ],
  'shop:purchase_replayed': [
    'Already recorded. No second purchase was made.',
    'That purchase is saved.',
    'It is already yours.',
  ],
  'market:browse': [
    'Look at the details before you decide.',
    'Listings are open.',
    'Some are better than others.',
  ],
  'market:listing_created': [
    'Listed.',
    'The details are there. Good.',
    'The listing is there. I noticed.',
  ],
  'profile:progress_view': [
    'A good record. I noticed.',
    'I do not compare profiles. There would not be much point.',
    'You have been consistent. Finally.',
    'That is better than I expected.',
  ],
  ballet: ['Again.', 'Better.', 'Posture.'],
  performance: ['Nice. I saw that.', 'You held the room.', 'The finish was clean.'],
  wardrobe: ['It is fine.', 'You chose that?', 'No, keep it. It suits you.'],
  profile: [
    'I noticed.',
    'I do not compare records. There would not be much point.',
    'Better than expected.',
  ],
  daily: ['Oh. You made it.', 'Claim recorded.', 'There. Done.'],
  shop: ['Interesting.', 'If you like it.', 'The details matter.'],
  inventory: ['All there.', 'I noticed the collection.', 'You have options.'],
  achievements: ['The record is below.', 'It is all there.', 'I noticed.'],
  market: [
    'The listing is there.',
    'Details matter.',
    'Some choices are more convincing than others.',
  ],
  help: ['Commands are listed below.', 'Choose one.', 'You asked. Here.'],
  balance: ['There it is.', 'Your balance is below.', 'Noted.'],
  ping: ['Here.', 'Still here.', 'I noticed.'],
};

export const NOELIA_PRESENCE = [
  'Oh.',
  'I noticed.',
  'Not competing. Just keeping score.',
  'I do not like attention. I do not need to ask for it.',
  'Interesting choice.',
  'If you like it.',
  'Standards are normal.',
  'I was being accurate.',
  'Was that supposed to be difficult?',
  'I do not compare myself to people.',
  'There would not be much point.',
  'Better.',
  'Finally.',
  'I do not see the problem.',
  'I am not competitive. I just prefer winning.',
  'You asked.',
  'No?',
  'It is fine.',
  'I noticed the effort.',
  'That works.',
  'Again.',
  'Posture.',
  'Très bien.',
  'No. Keep it. It suits you.',
] as const;
